import { checkSchema } from 'express-validator';

export const taskSchema = checkSchema({
	name: {
		in: 'body',
		errorMessage: 'Wrong name format',
		trim: true,
		isString: true,
		notEmpty: true,
		optional: true,
	},
	discipline: {
		in: 'body',
		errorMessage: 'Wrong discipline format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	// languageId:{
	// 	in: 'body',
	// 	errorMessage: 'Wrong languageId format',
	// 	trim: true,
	// 	isString: true,
	// 	optional: true,
	// 	notEmpty: true,
	// },
	rank: {
		in: 'body',
		errorMessage: 'Wrong rank format',
		isInt: true,
		optional: true,
		notEmpty: true,
	},
	tags: {
		in: 'body',
		errorMessage: 'Wrong tags format',
		optional: true,
	},
	allowContributors: {
		in: 'body',
		errorMessage: 'Wrong allowContributors format',
		trim: true,
		isBoolean: true,
		optional: true,
		notEmpty: true,
	},
	isPublished: {
		in: 'body',
		errorMessage: 'Wrong isPublished format',
		trim: true,
		isBoolean: true,
		optional: true,
		notEmpty: true,
	},
	description: {
		in: 'body',
		errorMessage: 'Wrong description format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	completeSolution: {
		in: 'body',
		errorMessage: 'Wrong complete solution format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	initialSolution: {
		in: 'body',
		errorMessage: 'Wrong initial solution format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	preloaded: {
		in: 'body',
		errorMessage: 'Wrong preloaded format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	testCases: {
		in: 'body',
		errorMessage: 'Wrong test cases format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
	exampleTestCases: {
		in: 'body',
		errorMessage: 'Wrong example test cases sample format',
		trim: true,
		isString: true,
		optional: true,
		notEmpty: true,
	},
});
