export const ConfigVariablesName = [
	'PORT',
	'SECRET_KEY',
	'TYPEORM_CONNECTION',
	'TYPEORM_HOST',
	'TYPEORM_PORT',
	'TYPEORM_USERNAME',
	'TYPEORM_PASSWORD',
	'TYPEORM_DATABASE',
	'TYPEORM_SSL',
];
