import { config } from 'dotenv';

config();

const ConfigVariables = process.env;

const {
	PORT,
	SECRET_KEY,
	TYPEORM_CONNECTION,
	TYPEORM_HOST,
	TYPEORM_PORT,
	TYPEORM_USERNAME,
	TYPEORM_PASSWORD,
	TYPEORM_DATABASE,
	TYPEORM_SSL,
	TYPEORM_SYNCHRONIZE,
	TYPEORM_LOGGING,
	TYPEORM_MIGRATIONS,
	COOKIE_NAME,
	COOKIE_SECRET,
	TYPEORM_ENTITIES,
	TYPEORM_MIGRATIONS_DIR,
	TYPEORM_ENTITIES_DIR,
} = ConfigVariables;

const ENV = {
	APP: {
		PORT,
		API_PATH: '/api',
	},
	JWT: {
		SECRET: SECRET_KEY,
		EXPIRES_IN: '30m',
		REFRESH_EXPIRES_IN: '30d',
	},
	COOKIE: {
		NAME: COOKIE_NAME,
		SECRET: COOKIE_SECRET,
		MAX_AGE: '30d',
		HTTP_ONLY: true,
	},
	DB: {
		DATABASE: TYPEORM_DATABASE,
		USERNAME: TYPEORM_USERNAME,
		PASSWORD: TYPEORM_PASSWORD,
		HOST: TYPEORM_HOST,
		PORT: TYPEORM_PORT,
		DIALECT: TYPEORM_CONNECTION,
		SYNCHRONIZE: TYPEORM_SYNCHRONIZE,
		LOGGING: TYPEORM_LOGGING,
		MIGRATIONS: TYPEORM_MIGRATIONS,
		ENTITIES: TYPEORM_ENTITIES,
		MIGRATIONS_DIR: TYPEORM_MIGRATIONS_DIR,
		ENTITIES_DIR: TYPEORM_ENTITIES_DIR,
		SSL: TYPEORM_SSL,
	},
};

export { ENV, ConfigVariables };
