export const social = [
	{
		title: 'Followers',
		id: 'followers',
		users: [
			{
				id: '90',
				rank: 4,
				imageSource: '',
				username: 'vasik',
				name: 'Vasya',
				clan: 'clan a',
				honor: 900,
			},
			{
				id: '91',
				rank: 4,
				imageSource: '',
				username: 'ivasik',
				name: 'Vasya',
				clan: 'clan a',
				honor: 900,
			},
			{
				id: '92',
				rank: 4,
				imageSource: '',
				username: 'vasik',
				name: 'Vasya',
				clan: 'clan a',
				honor: 900,
			},
			{
				id: '93',
				rank: 4,
				imageSource: '',
				username: 'vasik',
				name: 'Vasya',
				clan: 'clan a',
				honor: 900,
			},
		],
	},
	{
		title: 'Following',
		id: 'following',
		users: [
			{
				id: '95',
				rank: 4,
				imageSource: '',
				username: 'john',
				name: 'John',
				clan: 'clan b',
				honor: 900,
			},
			{
				id: '96',
				rank: 4,
				imageSource: '',
				username: 'petro',
				name: 'Petro',
				clan: 'clan b',
				honor: 900,
			},
			{
				id: '97',
				rank: 4,
				imageSource: '',
				username: 'chris',
				name: 'Chris',
				clan: 'clan a',
				honor: 900,
			},
		],
	},
	{
		title: 'Community',
		id: 'community',
		users: [
			{
				id: '98',
				rank: 4,
				imageSource: '',
				username: 'ge',
				name: 'George',
				clan: 'clan f',
				honor: 900,
			},
			{
				id: '99',
				rank: 4,
				imageSource: '',
				username: 'ja',
				name: 'James',
				clan: 'clan b',
				honor: 800,
			},
			{
				id: '100',
				rank: 4,
				imageSource: '',
				username: 'chris',
				name: 'Chris',
				clan: 'clan a',
				honor: 900,
			},
		],
	},
];
